name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tims-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: times-excel-reader

      - name: Install packages
        working-directory: times-excel-reader
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check code formatting
        working-directory: times-excel-reader
        run: |
          pre-commit install
          pre-commit run --all-files

      - uses: actions/checkout@v2
        with:
          repository: samwebster/times-ireland-model
          path: times-ireland-model

      - uses: actions/checkout@v2
        with:
          repository: MaREI-EPMG/times-ireland-model_gams
          path: times-ireland-model_gams

      - name: Convert ground truth DD to CSV
        working-directory: times-excel-reader
        run: |
          python utils/dd_to_csv.py ../times-ireland-model_gams/model ground_truth

      - name: Run tool and check output
        working-directory: times-excel-reader
        run: |
          python times_excel_reader.py
